package com.cfr.model;

import java.math.BigDecimal;
import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value="Dali", date="2561-09-28T14:13:51.249+0700")
@StaticMetamodel(TrnInvoice.class)
public class TrnInvoice_ {
	public static volatile SingularAttribute<TrnInvoice, String> active;
	public static volatile SingularAttribute<TrnInvoice, String> admissionTypeCode;
	public static volatile SingularAttribute<TrnInvoice, String> allocateDate;
	public static volatile SingularAttribute<TrnInvoice, String> allocateTime;
	public static volatile SingularAttribute<TrnInvoice, String> allocateUserId;
	public static volatile SingularAttribute<TrnInvoice, BigDecimal> amountAftDiscount;
	public static volatile SingularAttribute<TrnInvoice, BigDecimal> amountBefDiscount;
	public static volatile SingularAttribute<TrnInvoice, BigDecimal> amountOfDiscount;
	public static volatile SingularAttribute<TrnInvoice, String> batchNo;
	public static volatile SingularAttribute<TrnInvoice, String> currencyCode;
	public static volatile SingularAttribute<TrnInvoice, String> doctorCategoryCode;
	public static volatile SingularAttribute<TrnInvoice, String> doctorCode;
	public static volatile SingularAttribute<TrnInvoice, String> doctorNameEn;
	public static volatile SingularAttribute<TrnInvoice, String> doctorPoolCode;
	public static volatile SingularAttribute<TrnInvoice, BigDecimal> drAmt;
	public static volatile SingularAttribute<TrnInvoice, BigDecimal> drTaxAmt;
	public static volatile SingularAttribute<TrnInvoice, String> episodeNo;
	public static volatile SingularAttribute<TrnInvoice, String> executeDate;
	public static volatile SingularAttribute<TrnInvoice, String> executeTime;
	public static volatile SingularAttribute<TrnInvoice, BigDecimal> guaranteeAmt;
	public static volatile SingularAttribute<TrnInvoice, BigDecimal> guaranteeDlyCode;
	public static volatile SingularAttribute<TrnInvoice, BigDecimal> guaranteeMlyCode;
	public static volatile SingularAttribute<TrnInvoice, String> guaranteeNote;
	public static volatile SingularAttribute<TrnInvoice, BigDecimal> guaranteePaidAmt;
	public static volatile SingularAttribute<TrnInvoice, BigDecimal> hbnCode;
	public static volatile SingularAttribute<TrnInvoice, BigDecimal> hbnMethodAllocate;
	public static volatile SingularAttribute<TrnInvoice, String> hnNo;
	public static volatile SingularAttribute<TrnInvoice, String> hospitalCode;
	public static volatile SingularAttribute<TrnInvoice, BigDecimal> hpAmt;
	public static volatile SingularAttribute<TrnInvoice, String> invoiceDate;
	public static volatile SingularAttribute<TrnInvoice, String> invoiceNo;
	public static volatile SingularAttribute<TrnInvoice, String> invoiceType;
	public static volatile SingularAttribute<TrnInvoice, String> isGuarantee;
	public static volatile SingularAttribute<TrnInvoice, String> isGuaranteeFromAllocate;
	public static volatile SingularAttribute<TrnInvoice, String> isPaid;
	public static volatile SingularAttribute<TrnInvoice, String> isPartial;
	public static volatile SingularAttribute<TrnInvoice, String> isTaxFromAllocate;
	public static volatile SingularAttribute<TrnInvoice, String> isVoid;
	public static volatile SingularAttribute<TrnInvoice, String> isWriteOff;
	public static volatile SingularAttribute<TrnInvoice, String> mm;
	public static volatile SingularAttribute<TrnInvoice, String> nationalityCode;
	public static volatile SingularAttribute<TrnInvoice, String> nationalityDescription;
	public static volatile SingularAttribute<TrnInvoice, BigDecimal> norAllocateAmt;
	public static volatile SingularAttribute<TrnInvoice, BigDecimal> norAllocatePct;
	public static volatile SingularAttribute<TrnInvoice, String> note;
	public static volatile SingularAttribute<TrnInvoice, String> orderItemActive;
	public static volatile SingularAttribute<TrnInvoice, String> orderItemCode;
	public static volatile SingularAttribute<TrnInvoice, String> patientDepartmentCode;
	public static volatile SingularAttribute<TrnInvoice, String> patientLocationCode;
	public static volatile SingularAttribute<TrnInvoice, String> patientName;
	public static volatile SingularAttribute<TrnInvoice, String> payBy;
	public static volatile SingularAttribute<TrnInvoice, String> payorOfficeCode;
	public static volatile SingularAttribute<TrnInvoice, String> privateDoctorCode;
	public static volatile SingularAttribute<TrnInvoice, String> receiptDate;
	public static volatile SingularAttribute<TrnInvoice, String> receiptDepartmentCode;
	public static volatile SingularAttribute<TrnInvoice, String> receiptLocationCode;
	public static volatile SingularAttribute<TrnInvoice, String> receiptNo;
	public static volatile SingularAttribute<TrnInvoice, String> receiptTime;
	public static volatile SingularAttribute<TrnInvoice, String> receiptTypeCode;
	public static volatile SingularAttribute<TrnInvoice, BigDecimal> taxRate;
	public static volatile SingularAttribute<TrnInvoice, String> taxTypeCode;
	public static volatile SingularAttribute<TrnInvoice, BigDecimal> totalBillAmount;
	public static volatile SingularAttribute<TrnInvoice, String> transactionDate;
	public static volatile SingularAttribute<TrnInvoice, String> transactionNo;
	public static volatile SingularAttribute<TrnInvoice, String> updateDate;
	public static volatile SingularAttribute<TrnInvoice, String> updateTime;
	public static volatile SingularAttribute<TrnInvoice, String> updateUserCode;
	public static volatile SingularAttribute<TrnInvoice, String> yyyy;
}
